### ISSUE TITLE
letteropenerを導入する

### ISSUE THREAD

**Issue by Madogiwa0124** [Kosuke-Tsukada/DIC_thema_lesson#11]
手順は下記を参照
https://diveintocode.jp/diver/curriculums/16

[完了条件]
下記手順がエラーなく実行出来ることを確認する。
1. ユーザを作成
2. letteropenerの画面から有効化
3. 有効化したユーザでログインを行う

**Comment by norotime** [comment]
@Madogiwa0124 完了条件、などを記載してあげると良いですね！

**Comment by Madogiwa0124** [comment]
@norotime 
ありがとうございますm(_ _)m
記載してみました！

**Comment by norotime** [comment]
@Madogiwa0124 こんなこともできますよーー。

- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

**Comment by norotime** [comment]
↑
チェックリストサンプルです！
```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
```
